### ISSUE TITLE
Add CD Pipeline to be triggered on Pull Request

### ISSUE THREAD

**Issue by bryan-nice** [Senzing/senzing-api-server#110]
**Is your feature request related to a problem? 
The CD pipeline triggered on a Pull Request

**Describe the solution you'd like**
On every pull request will trigger this pipeline to verify the changes build correctly.

**Describe alternatives you've considered**
N/A

**Additional context**
Triggers on pull request only to master

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/senzing-api-server/pull/111
