### ISSUE TITLE
Update documentation for JDK version requirement

### ISSUE THREAD

**Issue by bryan-nice** [Senzing/senzing-api-server#113]
**Describe the bug**
After testing the build process using a CD pipeline, we discovered a specific JDK version is required. Otherwise, install latest JDK version will cause the maven build process to fail. This JDK version was not called out in documentation. We need the documentation updated to highlight and emphasize this dependency.

**Comment by barrycaceres** [comment]
Which documentation needs updating?  The beginning of the README under the header "Dependencies" reads as follows:

> To build the Senzing REST API Server you will need Apache Maven (recommend version 3.5.4 or later) as well as Java 1.8.x (recommend version 1.8.0_171 or later).

Is there another place we are looking to have this documented?

**Comment by bryan-nice** [comment]
thanks. I think that was what I was looking and my eye didn't pick up on it at the time.
