### ISSUE TITLE
add support for addRecordWithInfo

### ISSUE THREAD

**Issue by ryckowski** [Senzing/senzing-api-server#152]
**Is your feature request related to a problem? Please describe.**
Systems stores senzing entities ids, knowledge which entities have been modified is crucial

**Describe the solution you'd like**
add support for addRecordWithInfo

**Describe alternatives you've considered**

**Additional context**

**Comment by barrycaceres** [comment]
This is coming soon -- I am working on a 2.0 version of the API server which should be out this week and the "withInfo" and "reevaluate" are next on my list -- expect by the end of May 2020.
