### ISSUE TITLE
Improve documentation for init* args 

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-api-server#157]
In the using Demonstrate using Command Line section add sample commands for starting the api server, particularity the init* arguments showing file, JSON string and env var examples.

**Comment by barrycaceres** [comment]
Do you want me to add sample commands to the README file or to command-line help output or both?

**Comment by antaenc** [comment]
@barrycaceres Both please.

**Comment by barrycaceres** [comment]
This is being addressed in version 2.0 -- I already updated the usage string help output.  I will copy that output to the README as well and maybe provide additional examples there.
