### ISSUE TITLE
Wrong version referenced in example commands

### ISSUE THREAD

**Issue by msherman** [Senzing/senzing-api-server#158]
**Describe the bug**
In the Readme when it has you run the service the 1.8.0 version does not exist as the version that is built and compiled is 1.8.3
https://github.com/Senzing/senzing-api-server#running

**To Reproduce**
Run through the readme steps through mvn install and then run
`java -jar target/senzing-api-server-1.8.0.jar -help`

The 1.8.0 version does not exist

**Expected behavior**
The help info should be output when the proper jar is installed

**Screenshots**

**Desktop (please complete the following information):**

- OS: amazonlinux

**Additional context**
This was discovered while working with Michael Dockter

**Comment by barrycaceres** [comment]
This is fixed in the version 1.8.4 release.
