### ISSUE TITLE
Senzing Docker image creation issue - make: *** No rule to make target 'package'

### ISSUE THREAD

**Issue by visit2siva** [Senzing/senzing-api-server#161]
**Describe the bug**
Through Senzing Docker image file shared here, I have tried to create a senzing API server image in my docker instance (Windows10). I keep getting this error message saying " make: *** No rule to make target 'package' " 
Please, let me know if anyone provides a solution on this?
Step 13/26 : WORKDIR /senzing-api-server
 ---> Using cache
 ---> f4df57c344cc
Step 14/26 : RUN export SENZING_API_SERVER_JAR_VERSION=$(mvn "help:evaluate" -Dexpression=project.version -q -DforceStdout)  && make      SENZING_G2_JAR_PATHNAME=/senzing-api-server/${SENZING_G2_JAR_RELATIVE_PATHNAME}      SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION}      package  && cp /senzing-api-server/target/senzing-api-server-${SENZING_API_SERVER_JAR_VERSION}.jar "/senzing-api-server.jar"
 ---> Running in 068196039c5f
**make: *** No rule to make target 'package'.  Stop.
The command '/bin/sh -c export SENZING_API_SERVER_JAR_VERSION=$(mvn "help:evaluate" -Dexpression=project.version -q -DforceStdout)  && make      SENZING_G2_JAR_PATHNAME=/senzing-api-server/${SENZING_G2_JAR_RELATIVE_PATHNAME}      SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION}      package  && cp /senzing-api-server/target/senzing-api-server-${SENZING_API_SERVER_JAR_VERSION}.jar "/senzing-api-server.jar"' returned a non-zero code: 2**

**Desktop **
- OS: Windows 10
-Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
**Smartphone (please complete the following information):**

**Comment by docktermj** [comment]
As a test,  I just successfully performed the steps describe at https://github.com/Senzing/senzing-api-server#develop  on an Ubuntu 18.04 system.  So I'm wondering if this is an issue with a build on Windows.  

@visit2siva Just to make sure I'm following the path that you discovered the issue:  We're you using the instructions listed at https://github.com/Senzing/senzing-api-server#develop on a Windows 10 system?   Are there any other variations I should be aware of?

Thank you for reporting this issue.   It will take a little time, but I'll try to recreate on Windows.

**Comment by visit2siva** [comment]
Thanks @docktermj .  Yes I ran the below script in my local docker environment (Windows 10).
https://github.com/Senzing/senzing-api-server/blob/master/Dockerfile

**Comment by docktermj** [comment]
@visit2siva Did you clone the repository, set environment variables, and then run `make`?

What might be helpful is if you posted the commands you used to build the docker image.  I want to fix this, but I need to recreate first.

**Comment by visit2siva** [comment]
I installed the Docker Desktop version in my Windows10 laptop by following these steps.
https://docs.docker.com/docker-for-windows/install/

Docker version in my laptop is:
![image](https://user-images.githubusercontent.com/24992763/81700048-277efd00-9436-11ea-868e-87e48e7c1fbf.png)

**Comment by docktermj** [comment]
@visit2siva Did you clone the senzing-api-server repository according to instructions at https://github.com/Senzing/senzing-api-server#clone-repository?  Did you modify the instructions to account for the Windows platform?

**Comment by visit2siva** [comment]
@docktermj  Thanks for your input. Moreover, I have tried to build an image in the Linux server. I got a same error. I don't think it is Window issue. 

Step 14/26 : RUN export SENZING_API_SERVER_JAR_VERSION=$(mvn "help:evaluate" -Dexpression=project.version -q -DforceStdout)  && make      SENZING_G2_JAR_PATHNAME=/senzing-api-server/${SENZING_G2_JAR_RELATIVE_PATHNAME}      SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION}      package  && cp /senzing-api-server/target/senzing-api-server-${SENZING_API_SERVER_JAR_VERSION}.jar "/senzing-api-server.jar"
 ---> Running in 66b51f3cfd84
make: *** No rule to make target 'package'.  Stop.
The command '/bin/sh -c export SENZING_API_SERVER_JAR_VERSION=$(mvn "help:evaluate" -Dexpression=project.version -q -DforceStdout)  && make      SENZING_G2_JAR_PATHNAME=/senzing-api-server/${SENZING_G2_JAR_RELATIVE_PATHNAME}      SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION}      package  && cp /senzing-api-server/target/senzing-api-server-${SENZING_API_SERVER_JAR_VERSION}.jar "/senzing-api-server.jar"' returned a non-zero code: 2

**Comment by docktermj** [comment]
@visit2siva I'd like to try to recreate what you are doing.  Can you post:

1) Files used
2) Environment variables set
3) Commands issued

The symptoms exhibited make me think that this line isn't executing properly:   
https://github.com/Senzing/senzing-api-server/blob/9d8197517e043c43ea8371e09d173704125325b0/Dockerfile#L32

If that's true, then perhaps the docker build context isn't being specified properly.

We do see that the Make "package" target does exist in the Makefile:

https://github.com/Senzing/senzing-api-server/blob/9d8197517e043c43ea8371e09d173704125325b0/Makefile#L43-L44

**Comment by visit2siva** [comment]
@docktermj  As per your instruction, 
**Files used:** Dockerfile.txt  (attached here)
[Dockerfile.txt](https://github.com/Senzing/senzing-api-server/files/4623723/Dockerfile.txt)
**Environment Variable:**
[ec2-user@0be7b8a5f41cbac59 Senzing]$ export GIT_ACCOUNT=senzing
[ec2-user@0be7b8a5f41cbac59 Senzing]$ export GIT_REPOSITORY=senzing-api-server
[ec2-user@0be7b8a5f41cbac59 Senzing]$ export GIT_ACCOUNT_DIR=~/${GIT_ACCOUNT}.git
[ec2-user@0be7b8a5f41cbac59 Senzing]$ export GIT_REPOSITORY_DIR="${GIT_ACCOUNT_DIR}/${GIT_REPOSITORY}"
[ec2-user@0be7b8a5f41cbac59 Senzing]$ export SENZING_G2_DIR=/opt/senzing/g2
[ec2-user@0be7b8a5f41cbac59 Senzing]$ cd ${GIT_REPOSITORY_DIR}
     -bash: cd: /home/ec2-user/senzing.git/senzing-api-server: No such file or directory
**Docker Image build command used:**
sudo docker build  .

**Environment:**
Linux version:
Linux 4.14.171-105.231.amzn1.x86_64 x86_64

Docker version: Docker version 19.03.6-ce, build 369ce74

**Comment by docktermj** [comment]
@visit2siva On Step #2 of https://github.com/Senzing/senzing-api-server#clone-repository,  did you actually clone the repository?

Based on the error shown in your post:
> -bash: cd: /home/ec2-user/senzing.git/senzing-api-server: No such file or directory
It appears that the repository hasn't been cloned.

**Comment by visit2siva** [comment]
Yes @docktermj  you are correct. It is due to permission issues. After fixed the permission issue and cloned repo. I ran below command in a senzing-api-server folder and able to skip the error earlier blocked me. 
[ec2-user@0be7b8a5f41cbac59 senzing-api-server]**$ sudo docker build  .**

After that, it was stopped and throwing build failure error 
[ERROR] The specified file '/senzing-api-server/unknown' not exists
..
..
make: *** [Makefile:46: package] Error 1
The command '/bin/sh -c export SENZING_API_SERVER_JAR_VERSION=$(mvn "help:evaluate" -Dexpression=project.version -q -DforceStdout)  && make      SENZING_G2_JAR_PATHNAME=/senzing-api-server/${SENZING_G2_JAR_RELATIVE_PATHNAME}      SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION}      package  && cp /senzing-api-server/target/senzing-api-server-${SENZING_API_SERVER_JAR_VERSION}.jar "/senzing-api-server.jar"' returned a non-zero code: 2

**Comment by docktermj** [comment]
@visit2siva  In your post above, I noticed that you tried to build the docker image by using

> sudo docker build .

As you can see in Step 2 of https://github.com/Senzing/senzing-api-server#build-docker-image-for-development, the build is a little more sophisticated then that.  

The Makefile will help you along:  https://github.com/Senzing/senzing-api-server/blob/9d8197517e043c43ea8371e09d173704125325b0/Makefile#L89-L100

**Comment by visit2siva** [comment]
@docktermj  I tried it. but again it failed. since I am new to the docker environment, I may be missing something.

make: *** [Makefile:46: package] Error 1
The command '/bin/sh -c export SENZING_API_SERVER_JAR_VERSION=$(mvn "help:evaluate" -Dexpression=project.version -q -DforceStdout)  && make      SENZING_G2_JAR_PATHNAME=/senzing-api-server/${SENZING_G2_JAR_RELATIVE_PATHNAME}      SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION}      package  && cp /senzing-api-server/target/senzing-api-server-${SENZING_API_SERVER_JAR_VERSION}.jar "/senzing-api-server.jar"' returned a non-zero code: 2

**Comment by docktermj** [comment]
@visit2siva  When you are satisfied that we've helped you get past this issue, would you close the issue?

**Comment by visit2siva** [comment]
Sure I will do.

Thanks for your all help.
