### ISSUE TITLE
Logging and tracking Requests

### ISSUE THREAD

**Issue by NilayBhatt** [Senzing/senzing-api-server#162]
**Is your feature request related to a problem? Please describe.**
Serving data back and forth from the API without a means of proper logging of requests can be tedious during audits and debugging sessions.

**Describe the solution you'd like**
A standard logging of requests with date time would make tracking the usage of API very easy

**Describe alternatives you've considered**
Considering adding LoggerFactory to the API on the controllers

**Comment by barrycaceres** [comment]
We can look into this and there are definitely some options here.  The thing we have struggled with from an audit perspective is that currently we don't have user identification to associate a user with a request for audit logging.  We have remained flexible on user authentication by implementing as a micro service and letting external customer network components handle authenticating users and authorizing them for URL paths (e.g.: an HR user may have access to `POST /data-sources/EMPLOYEES/records` but not to `POST /data-sources/CUSTOMERS/records`).

So if we did any kind of auditing, the identity of the user would have to be asserted and trusted -- which implies a degree of trust between the wrapping API/web-app and the API Server.  Usually this can be achieved with running the Senzing API Server on `localhost` only and the wrapping API/web-app would run on the same host and would run on additional network interfaces.   Alternatively, we could look at enhancing with SSL Client cert authentication to only access to specific clients via SSL certificates.

**Comment by NilayBhatt** [comment]
Well the Logger can be abstract only tracking "what" is being done currently rather than the who (can still be done by extracting out as components for LDAP, OAuth, PING etc) such as "Using Searching by attributes: <SOME QUERY> @time stamp" would go a long way if enterprises are planning to forward logs and usage activity to other services such as Splunk or logstash

**Comment by missulmer** [comment]
This is a 'life in production operation' related feature for the Rest API. Adopting customers will need a way to maintain access, control, and audit for users engaging with the resolved data.

Right now, the work is not within a 4-8 window of releases.  If it needs to be,  run this request back through support and that will trigger conversations.
