### ISSUE TITLE
Senzing jar name change

### ISSUE THREAD

**Issue by msherman** [Senzing/senzing-api-server#165]
**Describe the bug**
If you follow the steps to download the senzing API server and install from github it is now installing version 1.8.4
https://github.com/Senzing/senzing-api-server

I don't see 1.8.4 in the releases. Is it currently released?
https://github.com/Senzing/senzing-api-server/releases

The reason I'm asking is we ran in to an issue when our automation script to deploy senzing on to an EC2 environment failed due to the jar no longer being senzing-1.8.3.jar after compile.

I fixed this locally in our automation script by changing the git clone command to this:
git clone https://github.com/Senzing/senzing-api-server.git --branch 1.8.3

A thought I had which might be worth looking in to is adding a <finalName>senzing-api-server<finalName> to the build section of the pom.xml then regardless of the version the jar would always be named senzing-api-server.jar and the automation script, and the documentation wouldn't need to be updated on each version change.

Here are the relevant steps to reproduce the issue. Because the jar file has the version in it then it breaks if an unexpected release appears.

```shell
git clone https://github.com/Senzing/senzing-api-server.git --branch 1.8.3
cd senzing-api-server
mvn install -DskipTests

cd ~/senzing-api-server
java -jar target/senzing-api-server-1.8.3.jar -httpPort "8080" -bindAddr all -iniFile /etc/opt/senzing/G2Module.ini -allowedOrigins "*" -enableAdmin
```

**Comment by docktermj** [comment]
@msherman Thanks for pointing that out.   My fault.  I'll add the release.

**Comment by docktermj** [comment]
@msherman   I've updated releases.  https://github.com/Senzing/senzing-api-server/releases

Does that solve the issue you are seeing?

**Comment by msherman** [comment]
@docktermj I think the overall issue is that the senzing jar name changes upon each release. I can understand this from both ends of the spectrum.

On one side its good to version lock.

On the other side it would be nice to make a singular update to a new version without having to also adjust the launching of the jar.

**Comment by docktermj** [comment]
For that part of the discussion, I'll turn the issue to @barrycaceres.

**Comment by docktermj** [comment]
@barrycaceres @msherman Has the issue of "senzing jar name" been resolved?   i.e. is this a "closed" issue?

**Comment by barrycaceres** [comment]
Making the change is simple, but I will need to evaluate the downstream effects.  I am hesitant to do it before the 2.0.0 release since we are so close and there are internal Senzing dependencies that reference version 2.0.0.  Also, I am not certain how Maven dependencies will react.  Perhaps defer to version 2.1.0 until we can confirm there are no downstream problems.

**Comment by barrycaceres** [comment]
This was discussed internally at length and we decided to keep the version number in the JAR file name as this seems to be standard.
