### ISSUE TITLE
The entity-paths & entity-networks return 500 on not-found records/entities, also SzRecordId encoding

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#17]
The entity-paths and entity-networks services incorrectly give 500 errors when an entity ID or record ID is not found.

Also, when specifying an SzRecordId you can only specify JSON but cannot specify a simple delimited string instead.  The following should be equivalent:

- `{"src":"PEOPLE","id":"12345ABC"}`
- `:PEOPLE:12345ABC`
- `_PEOPLE_12345ABC`

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/senzing-api-server/pull/18
