### ISSUE TITLE
Senzing API server provides empty attributes on searching the records

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/senzing-api-server#179]
Hi Team,

We have an issue with the senzing api. We need help from you to solve this.

We are working on another server with senzing with MSSQL database. It pulled all the way to the latest senzing version 2.0.1.

Our older server has senzing version : 1.15.3 (DB: Postgres)
The new server has the latest senzing version : 2.0.1 (DB: MSSQL)
![G2Version](https://user-images.githubusercontent.com/48215082/88508351-35d3c280-cffc-11ea-8a28-9e582645f9ca.png)

We have some data in our db and we get some response if we run this command in G2
**searchByAttributes '{"NAME_FULL":"Whitney New Japan Investors Ltd"}'**
and I attached the response below
![G2Command](https://user-images.githubusercontent.com/48215082/88508317-1e94d500-cffc-11ea-83ff-b28c99b97ea4.png)

But in the API server, all the attributes returning empty values except the name and entity id. We tried to solve this but we couldn't understand where the issue was.

We ran the following command in our servers 

curl -X GET "http://localhost:8250/entities?attrs=%7B%20%20%20%20%20%22NAME_FULL%22%3A%20%22%20Whitney%20New%20Japan%20Investors%2C%20Ltd%22%20%20%20%7D&featureMode=WITH_DUPLICATES&withFeatureStats=false&withInternalFeatures=false&forceMinimal=false&withRelationships=true&withRaw=false" -H "accept: application/json; charset=UTF-8" 
and I attached the responses from both from our old and new servers below in separate files. 
[old_server_search.txt](https://github.com/Senzing/senzing-api-server/files/4980181/old_server_search.txt)
[new_server_search.txt](https://github.com/Senzing/senzing-api-server/files/4980183/new_server_search.txt)

Can you help us solve this? Please let us know your availability so we can jump on a call asap. It's an emergency..!

Thanks.

**Comment by docktermj** [comment]
Hi @SaravananKalimuthu21 !

For starters, make sure you are using the nw `senzing/senzing-api-server:2.0.0` docker image with Senzing API 2.0.0+.  Earlier versions of the docker image only work with API 1.15.6 and below.

**Comment by SaravananKalimuthu21** [comment]
Hi Michael,

We upgraded the senzing/senzing-api-server version to 2.0.0 in our .yaml file and bring up the docker again and it worked.

It saved our big time.

Thanks a lot for the help.

**Comment by docktermj** [comment]
@SaravananKalimuthu21,

Terrific news!   If you are satisfied that the issue has been solved, please close this issue.
