### ISSUE TITLE
Yum senzingapi install with version 1.8.3

### ISSUE THREAD

**Issue by msherman** [Senzing/senzing-api-server#180]
**Describe the bug**
When trying to compile the 1.8.3 version of the Senzing API Server on a ec2 instance that has installed the senzingapi via yum we are receiving the following error:

` [ERROR] Failed to execute goal on project senzing-api-server: Could not resolve dependencies for project com.senzing:senzing-api-server:jar:1.8.3: Failed to collect dependencies at com.senzing:g2:jar:[1.14.0-SNAPSHOT,2.0.0-SNAPSHOT): No versions available for com.senzing:g2:jar:[1.14.0-SNAPSHOT,2.0.0-SNAPSHOT) within specified range -> [Help 1]`

**To Reproduce**
On an amazon linux 2 version run the following steps.
```shell
yum install https://senzing-production-yum.s3.amazonaws.com/senzingrepo-1.0.0-1.x86_64.rpm awscli groff tar git jq -y -q
amazon-linux-extras install postgresql11 vim epel java-openjdk11 -y -q 1> /dev/null

export SENZING_ACCEPT_EULA="I_ACCEPT_THE_SENZING_EULA"
yum -y -q install senzingapi
```

run the step to initialize the DB
Install the jar to maven

```shell
mvn install:install-file \
    -Dfile=$SENZING_G2_DIR/lib/g2.jar \
    -DgroupId=com.senzing \
    -DartifactId=g2 \
    -Dversion=$SENZING_G2_JAR_VERSION \
    -Dpackaging=jar

git clone https://github.com/Senzing/senzing-api-server.git --branch 1.8.3
java -jar target/senzing-api-server-1.8.3.jar -httpPort "8080" -bindAddr all -iniFile /etc/opt/senzing/G2Module.ini -allowedOrigins "*" -enableAdmin
```
the Java step will fail to run with the above error.

**Expected behavior**
The java step not to throw an error.

**Additional context**
To solve our problem we are thinking if we version lock the yum install of the senzingapi to 1.14.???? we would then be able to run the java service, but... because the script was rebooted we are thinking the database has upgraded to 2.0 and we are going to have further issues.

**Comment by docktermj** [comment]
@msherman 

I think I know what is going on, but first let me ask a background question.   On the machine where you did the `yum install`,  what is returned when you run this command:

```console
cat /opt/senzing/g2/g2BuildVersion.json
```

**Comment by docktermj** [comment]
@msherman 

If your result looks like this:

```console
$ cat /opt/senzing/g2/g2BuildVersion.json

{
    "PLATFORM": "Linux",
    "VERSION": "2.0.0",
    "BUILD_VERSION": "2.0.0.20197",
    "BUILD_NUMBER": "2020_07_15__12_20",
    "DATA_VERSION": "1.0.0"
}
```

Then it is a version issue.

The Senzing API Server 1.x.x versions work with the Senzing API 1.x.x versions.
The new Senzing API 2.0.0+ requires Senzing API server 2.0.0+

If you want to continue to use Senzing API Server 1.8.3, the last version of Senzing API supporting it is 1.15.6.
Reference:  https://senzing.com/releases/

If you use the most recent release of Senzing API Server (2.0.0) you can use Senzing API 2.0.0+.   

Note:  We use "Semantic Versioning"  (https://semver.org/)   The reason we released a new MAJOR of the Senzing API is because there are backward breaking changes.

**Comment by msherman** [comment]
@docktermj 
That is absolutely our issue. Assuming our database will need to be restored as well. Thank you for confirming our suspicions

**Comment by docktermj** [comment]
@msherman If this solves the issue you raised, please close the issue.   If there's more we can help with, please elaborate.

**Comment by docktermj** [comment]
@msherman Just checking in to see if we've solved your issue.   Let us know if there's more we can do to help.  If we don't hear back in a week, we'll close this issue.

**Comment by docktermj** [comment]
Closing.  Haven't heard back from customer.
