### ISSUE TITLE
Intermittent error 2062 from Senzing API

### ISSUE THREAD

**Issue by ndefreitas** [Senzing/senzing-api-server#193]
We're getting intermittent 2062 errors from the Senzing API Server; [SzError{code='2062', message='2062E|Requested lookup of [ETYPE_ID] using unknown value [0]. Value not found.'}]

Step to reproduce the behavior:
Load JSON DSRs using the POST method in rapid succession (one a second should be enough to replicate).

**Expected behavior**
All POST/AddEntity requests should succeed.

Senzing API Server Version: 1.8.3
Senzing Version: 1.15.1

**Comment by ndefreitas** [comment]
Per Senzing Support, updating G2Engine to version 1.15.6 first to see if that solves the issue. Will let you know if that solved it.

**Comment by barrycaceres** [comment]
This appears to be due to a data issue with missing "OBS_ENT" records in the repository.  I have assigned @jaeadams , @jbutcher21 and @brianmacy since they are much more knowledgable on what could cause this and how to fix it.

**Comment by jaeadams** [comment]
This is actually a problem in the G2 engine.  The API server is working correctly.

Fixes were made for this in the engine, with version 2.2.4.  To resolve the issue, the engine should be updated to that version or later.

Closing this as complete.
