### ISSUE TITLE
How do I find "DATA_SOURCE" when ruing API queries?

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/senzing-api-server#200]
How do I find "DATA_SOURCE" when ruing API queries?

e.g. 
```
curl -X GET "54.170.126.199:8250/data-sources/g2/records/1?withRaw=false" -H "accept: application/json; charset=UTF-8"
{"meta":{"httpMethod":"GET","httpStatusCode":404,"timings":{"overall":93,"enqueued":0,"nativeAPI":91,"nativeAPI:engine.getRecord":91},"timestamp":"2020-10-26T10:57:28.920Z","version":"2.0.1-39","restApiVersion":"2.0.0"},"links":{"self":"http://54.170.126.199:8250/data-sources/g2/records/1?withRaw=false"},"errors":[{"code":"27","message":"0027E|Unknown DATA_SOURCE value 'G2'"}]}%
```

**Comment by docktermj** [comment]
@barrycaceres , @antaenc @ryanbasile Need help on this one.

**Comment by barrycaceres** [comment]
I'm not sure I understand the context of the question, so I will try to answer with the basics and if that does not help, please respond and we can dive deeper.

The `DATA_SOURCE` field is what was loaded with the record.  For example, if you loaded records from your "CUSTOMER" database and used your "CUSTOMER_ID" as a record ID then a record you loaded might look like this:

```
{ "DATA_SOURCE": "CUSTOMERS", "RECORD_ID": "ABC123", "NAME_FULL": "Joe Schmoe", "PHONE_NUMBER": "702-555-1212", "EMAIL_ADDRESS": "joeschmoe@nowhere.com" }
```

Later if you wanted to search for that record you would identify it using `DATA_SOURCE=CUSTOMERS` and `RECORD_ID= ABC123 `.

For any record you load, the `DATA_SOURCE` you use must already be configured (i.e.: we do not configure them on the fly else typos would lead to lots of bad values).  You can get all configured data sources using:

`GET /data-sources`

You can configure a new data source (e.g.: "CUSTOMERS") *IF* you started the API server with the `-enableAdmin` option.  Assuming you started with that option you can do:

`POST /data-sources?dataSource=CUSTOMERS`

To configure multiple data sources at once (e.g.: "CUSTOMERS" and "WATCHLIST"):

`POST /data-sources?dataSource=CUSTOMERS&dataSource=WATCHLIST`

By default only the "TEST" data source is configured.  Examples of data sources (depending on use case) may be: (e.g.: "CUSTOMERS", "EMPLOYEES", "VIPS", "PASSENGERS", "WATCHLIST", "EMAIL_LIST", "REGISTERED_VOTERS", etc..).

The most basic use case would be to load a record to a data source like the one above for customer "Joe Schmoe" using:

`POST /data-sources/CUSTOMERS/records`

or

`PUT /data-sources/CUSTOMERS/records/ABC123`

And then query its *ENTITY* back so you could find which entity it resolved against (i.e.: check to see if it resolved against a record in the "WATCHLIST" data source)

`GET /data-sources/CUSTOMERS/records/ABC123/entity`

So generally, if you are querying you will want to know the data source of the record you are interested in and the record ID, so you can lookup information on that record or entity.

If you know data is loaded and you just want to search for entities then you can do that using the *search endpoint*.  The search endpoint can take the `attr` query parameter zero or more times or can alternatively take the `attrs` (plural) query parameter which on the URL would be a URL-encoded JSON object (easy to do programmatically, but hard to show in a example in my response here).  So for example, using the `attr` parameter to query entities that have `NAME_FULL` set to "Joe Schmoe" it would look like this (URL-encoded):

`GET /entities?attr=NAME_FULL:Joe+Schmoe`

The result would contain all entity records that match and each entity record would include record information (including data source values and record IDs).

I hope that helps, please let me know if I can be of further assistance.

**Comment by barrycaceres** [comment]
NOTE: You can also load records from bulk CSV files, JSON files (i.e.: JSON array of JSON objects) or a JSON-lines file (i.e.: one JSON object per line).  JSON-lines is probably the most common format folks use, but all of the above work and CSV is the easiest to throw something together.

The JSON fields you use for the JSON objects or in the flat CSV would be defined by the Senzing Generic Entity Specification.  Details on that (as well as examples) can be found here: https://senzing.zendesk.com/hc/en-us/articles/231925448-Generic-Entity-Specification

**Comment by docktermj** [comment]
@christianswanepoel Did we answer your question?   If so, would you be kind enough to close this issue.  If we haven't answered your question, please let us know what is still unclear.
