### ISSUE TITLE
Do I need the redoer / stream-loader when using apiserver?

### ISSUE THREAD

**Issue by christianswanepoel** [Senzing/senzing-api-server#201]
I am only accessing Senzing via the senzing-api-server. Do I need to have redoer / stream-loader running for senzing-api-server to work? In an effort to lower my AWS cost.

**Comment by docktermj** [comment]
@christianswanepoel  Once data is loaded into the Senzing Model (i.e. Database) then neither the stream-loader nor the redoer is needed.  The stream-loader's job is simply to take records from a queue (i.e. stream) and insert them into the database.   The redoer's job is to handled "deferred processing".     Both of these jobs are done once you've loaded your data.


**Special case:**   If you add data to your Senzing Model via the senzing-api-server, then you may want to run the redoer to handle any "deferred processing" introduce by a new insertion.  Once the log shows that no redo records are being processed, the redoer may be shut down until more records are added.

If this answers your question, please close the issue.  If there are any aspects I missed,  please let me know what I can help with.

**Comment by barrycaceres** [comment]
There is an important distinction here... If you are using the API Server to load your records then the API Server currently does not handle the redo queue -- i.e.: you may end up with a large redo queue after loading records, and those redos need to be processed.  We are looking at a way to add this functionality to the API server.  We just want to be careful that we do it in a way that works properly for our customers who are running multiple clustered API servers simultaneously -- so they don't step on each other's toes as they all try to redo the same records.

**Comment by barrycaceres** [comment]
We discussed this internally today and the consensus is that to avoid problems, the API Server will NOT handle the redo records and that a single Redo Docker image should be run alongside the API Server instances to handle the redos.

Does this satisfy your question for closing out this issue?

**Comment by christianswanepoel** [comment]
This is good with me - but is API Server configured to farm out requests to the redoer?

**Comment by docktermj** [comment]
Although the API server doesn't specifically do anything with respect to identifying records that need to be redo'd (made up name).  The "redoer" uses the Senzing Engine which identifies records that need to be redone.

Net effect:  The redoer process redo records independent of how they were loaded into Senzing.

**Comment by docktermj** [comment]
@christianswanepoel Can this issue be considered closed?

If not, please let us know what else we can do to help.

If so, please close it. If I don't hear from you in 7 days, I'll go ahead and close it.
