### ISSUE TITLE
Accommodate AWS Aurora Serverless disconnections

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-api-server#206]
Given

> Connections to an Aurora Serverless v1 DB cluster are closed automatically if held open for longer than one day. 

from [Limitations of Aurora Serverless v1](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations), make sure that the senzing-api-server is resilient in either reconnecting or exiting

**Comment by barrycaceres** [comment]
We believe that this will be resolved with Web Sockets -- also looking at adding asynchronous option for some endpoints to have them return 202 immediately and then background the work.

**Comment by jamietypovsky** [comment]
@docktermj are you currently testing this?

**Comment by docktermj** [comment]
@jamietypovsky I don't have a test for this.

**Comment by barrycaceres** [comment]
Need to check the error code from the native Senzing API read calls and if the error code indicates that the database connection was lost then we need to return an HTTP error code indicating retry is required after a certain amount of time (1 minute?)

**Comment by jamietypovsky** [comment]
@jaeadams can you please provide the correct error code?

**Comment by jaeadams** [comment]
These are the errors inside the engine.  So, error codes 1006 and 1007.

#define EAS_ERR_DATABASE_CONNECTION_FAILURE(errorInfo)   EASErrorMessage("1006E", "Database Connection Failure '{0}'", errorInfo)
#define EAS_ERR_DATABASE_CONNECTION_LOST(errorInfo)      EASErrorMessage("1007E", "Database Connection Lost '{0}'", errorInfo)

**Comment by jamietypovsky** [comment]
Fixed at the engine level.
