### ISSUE TITLE
Allow additional options

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-api-server#21]

**Comment by barrycaceres** [comment]
Michael, can you comment on what this means?

**Comment by docktermj** [comment]
Sorry for the scant information.   This was a quick fix to support arbitrary command-line options when invoking senzing-api-server.jar.   Other options are given specific environment variables.   This fix allows an invoker (docker run or docker-compose) to add additional command line options.

```console
CMD java -jar senzing-api-server.jar \
     -concurrency ${SENZING_CONCURRENCY} \
     -httpPort 8080 \
     -bindAddr ${SENZING_BIND_ADDR} \
     -iniFile ${SENZING_INI_FILE} \
     ${SENZING_OPTIONS}
```
Pull Requests:

- https://github.com/Senzing/senzing-api-server/pull/22
