### ISSUE TITLE
Documentation: Docker example additions for local Senzing project and issue with SQLite DB not being writeable

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-api-server#210]
The documentation for using Docker doesn't describe how to use this with a local project, only for the base senzing install which shouldn't be used. 

If I have multiple local projects I wish to use with the Docker image I need to:

1. Specify different paths for the exported SENZING_* env vars
2. I need to know to create an additional G2Module.ini_docker (for example) file to use with the  --iniFile arg that is shown or one of the other --ini* args

There is also an issue when using the SQLite DB found in the local project /var path specified by SENZING_VAR_DIR where the API server can't write to it and fails. Need to chmod the path/file with 777 for the container to come up. Otherwise the following error happens (tried the run as env var with no change):

```
ant - ~
--> sudo docker run   --interactive   --publish ${SENZING_API_SERVICE_PORT}:8250   --rm   --tty   --volume ${SENZING_DATA_VERSION_DIR}:/opt/senzing/data   --volume ${SENZING_ETC_DIR}:/etc/opt/senzing   --volume ${SENZING_G2_DIR}:/opt/senzing/g2   --volume ${SENZING_VAR_DIR}:/var/opt/senzing ${SENZING_RUNAS_USER_PARAMETER} senzing/senzing-api-server     -allowedOrigins "*"     -bindAddr all     -concurrency 10     -httpPort 8250     -iniFile /etc/opt/senzing/G2Module.ini_docker
os.arch        = amd64
os.name        = Linux
user.dir       = /app
user.home      = ?
java.io.tmpdir = /tmp
SUPPORT DIR: /opt/senzing/data
SQLITE3 ERROR: ((1544:attempt to write a readonly database))
java.lang.RuntimeException: Failed to initialize with specified initialization parameters.


Operation Failed : G2ConfigMgr.initV2
Error Code       : 1001
Reason           : 1001E|Critical Database Error '(1544:attempt to write a readonly database)'

Initialization parameters:

{"SQL":{"CONNECTION":"sqlite3://na:na@/var/opt/senzing/sqlite/G2 ... [truncated]


	at com.senzing.api.server.SzApiServer.getConfigType(SzApiServer.java:1926)
	at com.senzing.api.server.SzApiServer.<init>(SzApiServer.java:1540)
	at com.senzing.api.server.SzApiServer.<init>(SzApiServer.java:1414)
	at com.senzing.api.server.SzApiServer.initialize(SzApiServer.java:1291)
	at com.senzing.api.server.SzApiServer.main(SzApiServer.java:1211)
Failed to initialize with specified initialization parameters.


Operation Failed : G2ConfigMgr.initV2
Error Code       : 1001
Reason           : 1001E|Critical Database Error '(1544:attempt to write a readonly database)'

Initialization parameters:

{"SQL":{"CONNECTION":"sqlite3://na:na@/var/opt/senzing/sqlite/G2 ... [truncated]



ant - ~
```

@docktermj

**Comment by jamietypovsky** [comment]
@docktermj should this be part of the community project?

**Comment by docktermj** [comment]
@jamietypovsky Information that crosses repository boundaries is kept in https://github.com/Senzing/knowledge-base.

However, the documentation requested seems like it could be somewhere in the top level README.md file or someplace in the `/docs` directory.

**Comment by jamietypovsky** [comment]
Cancelling.  We do not support SQLite shared to a Docker image.
