### ISSUE TITLE
Building docker image - 2 'unknown vars' in dockerfile

### ISSUE THREAD

**Issue by harkinj** [Senzing/senzing-api-server#212]
Hi,
I'm trying to build the docker image for the rest api using :
docker build --tag senzing/senzing-api-server .

I've already built locally the 2 images it depends on :
senzing/senzing-base
senzing/base-image-debian

The error I get is -
ERROR] The specified file '/senzing-api-server/unknown' not exists
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.134 s
[INFO] Finished at: 2021-02-10T17:20:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install-file (default-cli) on project senzing-api-server: The specified file '/senzing-api-server/unknown' not exists -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/con

It has something to do with these 2 vars in the dockerfile -
ARG SENZING_G2_JAR_RELATIVE_PATHNAME=unknown
ARG SENZING_G2_JAR_VERSION=unknown
What should these 2 values be?
Also I'm looked at this dockerfile and the dockerfiles for the other 2 images mentioned and none of them actually install G2 lib and Java sdk so I think I'm missing a step or something :)
What is it ?
Thanks for your time.
Regards
John

**Comment by docktermj** [comment]
Hi @harkinj!

The building of `senzing/senzing-api-server` is a little special in that the `g2.jar` file needs to be available to the build.  Which means that Senzing needs to be installed on the local host because the file is located at `g2/lib/g2.jar'

The instructions we use to build  `senzing/senzing-api-server` are at https://github.com/Senzing/senzing-api-server#build-docker-image-for-development

Does that help move the ball forward?

**Comment by harkinj** [comment]
Hi,
Thanks for the info and your time.
Unfortunately It doesn't really move things along - at least in my mind :).
Putting something on the host ( I'm using a Mac and as per https://senzing.zendesk.com/hc/en-us/articles/115010259947 its not supported)  I believe defeats the purpose of using docker and images.
I want a stand alone image with the REST API on it and all its software dependencies on it. I then would like to run the image and setup some ENV vars containing a database connection string, Port etc  and off it goes.
Can I create such a thing?
Would then hope to use the image to deploy in a K8s cluster in the future so can scale it out etc.
Thanks again for your time.
Regards
John

**Comment by docktermj** [comment]
Hi @harkinj 

Maybe I'm missing something in your original post.  So permit me to explore this space a little:

We do have a pre-built `senzing/senzing-api-server` on DockerHub for your use.  It can be seen at https://hub.docker.com/r/senzing/senzing-api-server.  So if you want to use the "out-of-the-box" docker image,  it's already built for you.

My initial reply about how the Dockerfile is used to build `senzing/senzing-api-server` does create a single docker image with no runtime dependencies.  The dependency, `g2.jar`, is a build time only dependency.  

If you are familiar with Docker multistage builds, you can see that the actual building of `senzing-api-server.jar` is done in an initial stage (https://github.com/Senzing/senzing-api-server/blob/0ff39eabf3573958db5de0161525ff62e050ad61/Dockerfile#L4-L43) and then is copied into the final stage (https://github.com/Senzing/senzing-api-server/blob/0ff39eabf3573958db5de0161525ff62e050ad61/Dockerfile#L84)   Meaning that the `g2.jar` file isn't even in the final docker image.  It has been incorporated into the `senzing-api-server.jar`.

Were `g2.jar` on a Maven, Gradle, etc. repository,  the step of having a separate install of Senzing to get the `g2.jar` locally would not be needed.   We just haven't decided to put `g2.jar` on such repository yet.

So yes, you can create such a thing,  just remember that `g2.jar` isn't needed on your Kubernetes system,  it will be built into the `senzing-api-server.jar` file on the `senzing/senzing-api-server` docker image.

For more information on using Senzing in a Kubernetes environment, visit https://github.com/Senzing/kubernetes-demo   It shows how to use our Helm Charts to deploy the Docker images placed on DockerHub.

**Comment by harkinj** [comment]
Hi,
Thanks for the prompt response  and it has clarified things greatly.
Its great we can have a stand alone image with no runtime dependencies.
The one piece of the puzzle that i'm missing is that I see nothing in the dockerfiles that copies over the native libs to the image that I believe the java code in the g2.jar need/wrap?
Hope that makes sense.
Regards
John

**Comment by docktermj** [comment]
Hi @harkinj !

To keep our Docker images as small as we can and facilitate migration, the docker containers mount a file system that contains the Senzing binaries.   In Kubernetes parlance, we install the Senzing binaries onto a Persistent Volume (PV) and then mount that same persistent volume across all docker containers that require the Senzing binaries.

Examples of this can be seen in our kubernetes demo at:
1. https://github.com/Senzing/kubernetes-demo/tree/master/docs/helm-rabbitmq-postgresql#create-persistent-volume
1. https://github.com/Senzing/kubernetes-demo/tree/master/docs/helm-rabbitmq-postgresql#deploy-senzing-rpm

**Comment by harkinj** [comment]
Hi,
Thanks very much.
I'm striving for a stand alone image with as few/no 'external' dependencies (even a K8s PV)  other than the external database.
I've looked  at the links you have pointed me at and the
'Non-root container method' seems complex (at least to me)  and seems to run another image(senzing-base) which has to be manually updated with files from a local image. I think the senzing-base pod  is then the PV?  I'm no K8s expert but seems a bit complex.
That said would either :
1) updating the dockerfile for the senzing-api-server to run the apt commands as mentioned in https://docs.senzing.com/quickstart/   OR
2) have the Senzing binaries stored 'somewhere' that can be used as the source of a copy command that is used in the dockerfile and just copy the files over into the relevant dirs on the image during image creation.

work and get me a 'totally' stand alone image.

Thanks again for your time.
Regards
John

**Comment by docktermj** [comment]
Hi @harkinj !

If you want to wrap an existing docker image with a "baked in" version of the Senzing API binaries, take a look at https://github.com/Senzing/docker-wrap-image-with-senzing-apt

It can be used to bake in Senzing binaries into any docker image.

**Comment by harkinj** [comment]
Hi,
Thanks for the info and quick response.
https://github.com/Senzing/docker-wrap-image-with-senzing-apt. depends on another image Senzing/docker-init-container  which we would have to built  + senzing-base ......
Ideally we would like:
A single dockerfile , no dependencies(other than relevant Linux base image) that creates an image with G2 apis fully baked in and ready to be used. Perhaps pass in an G2 api version to use which would be handy.
We could then use this as a base image into which we could layer our G2 api based applications; knowing that the base image has G2 installed would help enourmously and limit the amount of images we would need to mange to a manageable amount and be easy for devs to understand and manage.
Hope that makes sense.
I don't believe such a dockerfile exists?
If not could one possibly be created.?
Thanks again for your great support.
Regards
John

**Comment by docktermj** [comment]
Hi @harkinj 

You are correct, neither a Dockerfile nor docker image exists for the customization you seek.   That shouldn't prevent you from customizing your own Dockerfile / Docker image.  Many of our customers have looked at our Dockerfiles and have created their own.

As for  what is seen in the Senzing GitHub Community, it's been focused on single-purpose docker images that can be combined and independently scaled via platforms like docker-compose, Kubernetes, OpenShift, AWS ECS, etc.   This follows Docker's guidance:

>  It is generally recommended that you separate areas of concern by using one service per container. 
> -- [Run multiple services in a container](https://docs.docker.com/config/containers/multi-service_container/)

Each Dockerfile demonstrates an independent aspect of what can be added to a "Senzing stack".  They are also crafted for educational purposes so that if a customer wants to create their own Dockerfile / docker images, they have a model of how to create each aspect.

You are seeking more of a monolith docker image, which is a fine customization for individual customers, but creates versioning, scaling, and combinatorial issues for what is seen in the GitHub Community.

So,  do think about creating a custom Dockerfile tailored to your needs.

**Comment by docktermj** [comment]
@harkinj Is there any more information you need for this issue?    If not, can you close the issue.   Thank you!

**Comment by harkinj** [comment]
Hi,
sorry for delay and thanks for all your help.
I've got the info i need.
Regards
John
