### ISSUE TITLE
Support POST endpoint for entity searchByAttributes

### ISSUE THREAD

**Issue by knquintana** [Senzing/senzing-api-server#215]
**Is your feature request related to a problem? Please describe.**
We'd like to start using the entity searchByAttributes functionality but, given that some of our record features are sensitive data, we don't feel comfortable passing them in as query parameters to the GET /entities?attrs= endpoint.

**Describe the solution you'd like**
The addition of a POST /entities endpoint that will allow us to pass in search attrs in the request body.

**Additional context**
senzing api version: 1.15.0 
https://hub.docker.com/r/senzing/senzing-api-server/ version: 1.8.2

**Comment by barrycaceres** [comment]
I should be able to address this with a new release within the next 10 days.

**Comment by barrycaceres** [comment]
This is addressed in version 2.5.0 of the Senzing REST API Server
