### ISSUE TITLE
Return something when accessing "/"

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-api-server#220]
**Is your feature request related to a problem? Please describe.**

When the Senzing API server is running, a URL like this works:  `http://localhost:8250/heartbeat`

However `http://localhost:8250/` returns an HTTP 404.   This somewhat fakes out a customer that is wondering if the API server is functioning correctly.

Can the '/' path return some type of JSON that is helpful in guiding the user to supported URLs.    Maybe JSON-API has an idea of what the "opening" JSON should look like.

**Comment by jamietypovsky** [comment]
@barrycaceres  please notify Michael and Ron once this has been released.

**Comment by barrycaceres** [comment]
Resolved in version 2.7.0 release.
