### ISSUE TITLE
update Senzing base to 1.6.0 

### ISSUE THREAD

**Issue by roncewind** [Senzing/senzing-api-server#227]

**Comment by roncewind** [comment]
Mike I'm not sure what we want to do with updating this docker file.

**Comment by docktermj** [comment]
In this "multi-stage" Dockerfile:

1) Change
https://github.com/Senzing/senzing-api-server/blob/d3fed8a14413bf5ba9fec0aaf7546040e46845af/Dockerfile#L1
to 
```Dockerfile
ARG BASE_IMAGE=senzing/senzing-base:1.6.0
```

2) Change both `REFRESHED_AT` timestamps

3) Change
https://github.com/Senzing/senzing-api-server/blob/d3fed8a14413bf5ba9fec0aaf7546040e46845af/Dockerfile#L55
to
```Dockerfile
      Version="2.6.2"
```

Put those changes in a branch.   Then see if you can build the Dockerfile using the instructions at https://github.com/Senzing/senzing-api-server#develop

**Comment by roncewind** [comment]
PR merged

**Comment by docktermj** [comment]
Another "gotcha" is https://github.com/Senzing/senzing-api-server/blob/e4fadbd6b5229c98c2e096a0e09f31480f21dbf7/Makefile#L22
