### ISSUE TITLE
Compress Senzing response using GZip

### ISSUE THREAD

**Issue by pandeyashok** [Senzing/senzing-api-server#228]
We see Senzing response taking time to transfer data between the server and client applications. Allow Senzing responses to return GZip response when the data in the response is more than 1MB.

**Comment by barrycaceres** [comment]
I will experiment with larger response sizes, but I was under the impression that the embedded Jetty server would automatically handle this if the client specified "Accept-Encoding: gzip" in the request headers.   I will test to see if that is NOT the case and if not, will figure out how to enable the various response encodings for compression algorithms.

**Comment by barrycaceres** [comment]
Should have this resolved with a new release within the week.

The modification to add Jetty's GzipHandler to the embedded Jetty setup seems to resolve this.

**Comment by barrycaceres** [comment]
Resolved in version 2.7.0 release
