### ISSUE TITLE
Add CSV/JSON entity ID parameters as alternate to multi-query params 

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#23]
Some operations are taking multiple query parameters to specify entity identifiers.

However, in some cases it is easier to specify a CSV value or a JSON array.

Would be great if alternate parameters existed that expected JSON arrays or CSV arrays.

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/senzing-api-server/pull/24
