### ISSUE TITLE
senzing-api-server failed scan, but GitHub reports free of CVEs

### ISSUE THREAD

**Issue by jp15310** [Senzing/senzing-api-server#257]
**Ran a Docker Scan and got many CVEs**
Organization:      jp15310
Package manager:   deb
Project name:      docker-image|senzing/senzing-api-server
Docker image:      senzing/senzing-api-server:latest
Platform:          linux/amd64
Base image:        debian:10.11
Licenses:          enabled

Tested 414 dependencies for known issues, found 232 issues.

Base Image    Vulnerabilities  Severity
debian:10.11  65               2 critical, 11 high, 6 medium, 46 low

Recommendations for base image upgrade:

Major upgrades
Base Image       Vulnerabilities  Severity
debian:bullseye  37               1 critical, 2 high, 0 medium, 34 low

Alternative image types
Base Image      Vulnerabilities  Severity
debian:11-slim  37               1 critical, 2 high, 0 medium, 34 low

**To Reproduce**

1. From a command line while logged on DockerHub, ran the following:
> docker scan senzing/senzing-api-server:latest > senzing_report.txt
2. See error in the senzing_report.txt file

**Expected behavior**
I would expect to see no Medium, HIgh, or Critical Vulnerability of the base image.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser chrome
- Version 97.0.4692.71

**Additional context**
See detailed scan results in attached file
[senzing_report.txt](https://github.com/Senzing/senzing-api-server/files/7854578/senzing_report.txt)

**Comment by roncewind** [comment]
This has been address as much as possible with PR:   https://github.com/Senzing/senzing-api-server/pull/262
