### ISSUE TITLE
[DEVELOPMENT BLOCKER] Senzing API Server URL IpAddress:8250 cannot be displayed

### ISSUE THREAD

**Issue by lee-jia-mei** [Senzing/senzing-api-server#295]
We are in the midst of setting up connecting to the Senzing API and have hit a road block, appreciate if you point us to some resources that we can further debug. The issue is that the Senzing API Server URL IpAddress:8250 cannot be displayed, as a results I cannot connect and call the api (https://senzing.zendesk.com/hc/en-us/articles/4673553841811-Senzing-in-3-API-Calls-RESTful-API-2-x-)

We have performed the installation successfully:
Installed Senzing on RHEL (https://senzing.zendesk.com/hc/en-us/articles/115002408867-Quickstart-Guide)
Changed the DB from default SQLite to Postgresql (https://senzing.zendesk.com/hc/en-us/articles/360026348454-Setup-PostgreSQL-on-RedHat-CentOS)
Set up Senzing API Server (https://github.com/Senzing/senzing-api-server)
Web Application Installation (https://github.com/Senzing/entity-search-web-app/tree/d37bdd980fc8d775de008ceeb07a0ff7df3ddc91). 

I am able to start senzing api server successfully ![image](https://user-images.githubusercontent.com/104043724/177559794-f1dd7884-c133-406f-8b7f-acb9b04cf343.png) without any error, however, when accessing IpAddress:8250 on chrome, the page cannot be displayed.  In addition, I was able to start and access the senzing web application by accessing IpAddress:4200 on chrome. 

The file hosts : 
![image](https://user-images.githubusercontent.com/104043724/177561090-e8a2aa07-416a-4dc2-9c70-a870d40c5ff1.png)

To start senzing api server, these codes are ran:
cd ~/senzing
source setupEnv
java -jar /opt/senzing/senzing-api-server/target/senzing-api-server-2.8.5.jar  --ini-file /home/senzing/senzing/etc/G2Module.ini --http-port 8250

To start senzing web application, these codes are ran:
cd /opt/senzing/entity-search-web-app
npm start

**Comment by brianmacy** [comment]
I don't know if it is the cause but your /etc/hosts is clearly wrong.  The proper localhost ipv4 is 127.0.0.1 and not 0.0.0.0

**Comment by brianmacy** [comment]
Are you trying to connect to the API server from that box or from a remote box?
Note that the screenshot says that the REST API is running at 127.0.0.1:2080 and not port 8250.

Please provide the output of `netstat -na | grep LISTEN`

**Comment by lee-jia-mei** [comment]
Hi Brian, 

Thank you for the prompt reply. 

We managed to get it to work by running java -jar /opt/senzing/senzing-api-server/target/senzing-api-server-2.8.5.jar  --ini-file /home/senzing/senzing/etc/G2Module.ini --http-port 8250 **--bind-addr <ip_address>**

RESOLVED
