### ISSUE TITLE
'command not found' error

### ISSUE THREAD

**Issue by chriscorrea** [Senzing/senzing-api-server#318]
**Description**
Running the docker container returns 'command not found' error.

**To Reproduce**
1. [Initialize Senzing with Docker](https://github.com/Senzing/knowledge-base/blob/main/HOWTO/initialize-senzing-with-docker.md)
2. Complete steps to [demonstrate REST API using Docker](https://github.com/Senzing/senzing-api-server#demonstrate-using-docker)
3. Run the docker container, for example:
```
docker run \
  --interactive \
  --publish ${SENZING_API_SERVICE_PORT}:8250 \
  --rm \
  --tty \
  --volume ${SENZING_DATA_VERSION_DIR}:/opt/senzing/data \
  --volume ${SENZING_ETC_DIR}:/etc/opt/senzing \
  --volume ${SENZING_G2_DIR}:/opt/senzing/g2 \
  --volume ${SENZING_VAR_DIR}:/var/opt/senzing \
  senzing/senzing-api-server -version

```
5. See the following error: `/app/docker-entrypoint.sh: line 13: -version: command not found`

**Context**
`cat ${SENZING_VOLUME}/g2/g2BuildVersion.json` returns:
```
{
    "PLATFORM": "Linux",
    "VERSION": "3.1.2",
    "BUILD_VERSION": "3.1.2.22182",
    "BUILD_NUMBER": "2022_07_01__20_07",
    "DATA_VERSION": "3.0.0"
}
```

**Comment by docktermj** [comment]
Hi @chriscorrea 

The entry point script  https://github.com/Senzing/senzing-api-server/blob/main/rootfs/app/docker-entrypoint.sh. shows that when overwriting the command (https://github.com/Senzing/senzing-api-server/blob/67e4b9c6ae6ac0b6b84362aaf956865b78326abe/Dockerfile#L114).  You must overwrite the complete command, not just the command-line options.  So it would be something like:
```console
docker run \
  --interactive \
  --publish ${SENZING_API_SERVICE_PORT}:8250 \
  --rm \
  --tty \
  --volume ${SENZING_DATA_VERSION_DIR}:/opt/senzing/data \
  --volume ${SENZING_ETC_DIR}:/etc/opt/senzing \
  --volume ${SENZING_G2_DIR}:/opt/senzing/g2 \
  --volume ${SENZING_VAR_DIR}:/var/opt/senzing \
  senzing/senzing-api-server java -jar  senzing-api-server.jar -version
```

**Comment by docktermj** [comment]
Note, this behavior will be improved via https://github.com/Senzing/senzing-api-server/issues/322

**Comment by docktermj** [comment]
@chriscorrea Based on your issue, we've improved the syntax used with the Docker image.  We delivered the fix via https://github.com/Senzing/senzing-api-server/issues/322  With the `senzing/senzing-api-server:3.3.3`, you can pass in parameters in the manner that you requested above.

If this is satisfactory, please close this issue.   If it isn't please elaborate on your request.  Thank you for bringing this to our attention!

**Comment by chriscorrea** [comment]
Thank you for the clarification and for working toward a solution that is consistent with the documentation!
