### ISSUE TITLE
Improve documentation for overriding server command

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-api-server#322]
Recent issue: https://github.com/Senzing/senzing-api-server/issues/318#issuecomment-1213197163. Add to documentation users need to do this when overriding the command to start the server.

**Comment by docktermj** [comment]
With the fix, an example invocation is this:

```console
docker run \
  --env SENZING_ENGINE_CONFIGURATION_JSON \
  senzing/senzing-api-server:latest \
    --skip-engine-priming true \
    --skip-startup-perf true    
```

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/senzing-api-server/pull/360
