### ISSUE TITLE
Docs need to instruct user to restart on config changes

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#33]
Config functions produce stale results if the config changes after restart.  Documentation should instruct the user to restart the server with config changes.

**Comment by barrycaceres** [comment]
Auto reinitialization of the config has been implemented, nullifying this deficiency

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/senzing-api-server/pull/34
2. https://github.com/Senzing/senzing-api-server/pull/35
