### ISSUE TITLE
Change to entrypoint breaks SenzingGo. Revert change temporarily. 

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-api-server#361]
Recent change to entrypoint has broken SenzingGo. Revert the change until version 3.3. For 3.3 Ant & Michael to implement new entrypoint and the new version of SenzingGo.

**Comment by docktermj** [comment]
This will revert the change seen in https://github.com/Senzing/senzing-api-server/pull/360

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/senzing-api-server/pull/362
