### ISSUE TITLE
Inconsistent minimum value for parameter maxDegrees of GET /entity-paths 

### ISSUE THREAD

**Issue by nntzuekai** [Senzing/senzing-api-server#417]
Hello, 

I discovered an inconsistency between the minimum value for parameter **maxDegrees** of endpoint **GET /entity-paths** in the specification and in code. 

In the specification (https://github.com/Senzing/senzing-rest-api-specification/blob/4f1bb86a4d9749b1689a4f3eef8ebea2cc94b5dc/senzing-rest-api.yaml#L2013), it specifies that the minimum value of **maxDegrees** is 0. According to OpenAPI specification, if `exclusiveMinimum` is not specified, by default the minimum is included in the range, which means it allows **maxDegrees**>=0. However, in the code (https://github.com/Senzing/senzing-api-server/blob/main/src/main/java/com/senzing/api/services/EntityGraphServices.java#L167), it requires **maxDegrees**>=1, i.e., **maxDegrees**>0. As suggested by the description of the parameter, the latter seems to be the correct constraint on **maxDegrees** and probably `exclusiveMinimum: true` should be added there.

Can you please check and confirm this?

Thanks!

**Comment by barrycaceres** [comment]
I need to look into this minimum -- I know we made a recent update here -- I will confirm it is valid and respond.

**Comment by barrycaceres** [comment]
For `/entity-networks` the minimum value is zero (0), however, as you caught for `/entity-paths` the minimum value is one (1).  The description of the `maxDegrees` parameter for `/entity-paths` states this, but the coded minimum in the spec was mistakenly set at zero (0).  I am updating the specification accordingly.

**Comment by barrycaceres** [comment]
This is addressed in version `3.4.0` release of `senzing-rest-api-specification`

**Comment by nntzuekai** [comment]
Thank you for your clarification!
