### ISSUE TITLE
SenzingService.searchEntities() -> Server is down !

### ISSUE THREAD

**Issue by sridatta-mallagari** [Senzing/senzing-api-server#441]
**Describe the bug**
ERROR c.d.a.g.v.s.s.impl.SenzingService - ## SenzingService.searchEntities() -> Exception occurred at SenzingService.searchEntities() -> exception: com.dataeconomy.aml.graph.visualization.handler.AMLException: Exception occurred at SenzingService.searchEntities() -> Server is down !

We are frequently, seeing the above message when invoking Senzing from the Java. Kindly could you help with steps in fixing the issue.
Our Senzing is running on the AWS, with application running on AWS ECS & DB on the Aurora PostgreSQL.
API, Swagger, SSHD & WebApp tasks on the ECS are running without any issues when issue has occured.

We are accessing the load balancer which are backed by the ECS Tasks, to call Senzing API's .

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sridatta-mallagari** [comment]
ERROR c.d.a.g.v.s.s.impl.SenzingService - ## SenzingService.searchEntities() -> Exception occurred at SenzingService.searchEntities() -> exception: com.dataeconomy.aml.graph.visualization.handler.AMLException: Exception occurred at SenzingService.searchEntities() -> Server is down !

We are frequently, seeing the above message when invoking Senzing from the Java. Kindly could you help with steps in fixing the issue.

Our Senzing is running on the AWS, with application running on AWS ECS & DB on the Aurora PostgreSQL.

API, Swagger, SSHD & WebApp tasks on the ECS are running without any issues when issue has occured.

We are accessing the load balancer which are backed by the ECS Tasks, to call Senzing API's .

**Comment by docktermj** [comment]
@sridatta-mallagari Need a little clarification.

I've scanned Senzing's code for "SenzingService" and didn't find it.  Is it fair to assume that "SenzingService" is code that you have written?

Is the issue that `SenzingService.searchEntities()`, isn't finding a running Senzing `senzing-api-server` service?   If so, two things come to mind:

1. The senzing-api-server is dead or non-responsive
2. The load balancer is involved in the issue (perhaps a timeout issue)

Can you attach the AWS log(s) for the ECS container(s) that run the senzing-api-server?

**Comment by barrycaceres** [comment]
We are definitely going to need logs from the `senzing-api-server` if we are going to help guide you in solving this.  We don't really offer support on the open source components like `senzing-api-server`, but when it reports errors we do like to get them fixed.  Only problem here is that I am not seeing an error message that the `senzing-api-server` produces.

**Comment by barrycaceres** [comment]
We have not heard a response on this so we will close it in two weeks if no response with logs.

**Comment by barrycaceres** [comment]
Closing due to lack of response from reporter
