### ISSUE TITLE
Add version endpoint 

### ISSUE THREAD

**Issue by antaenc** [Senzing/senzing-api-server#48]
No endpoint currently to return engine version details. Add an endpoint to return the version details, e.g.:

{
  "VERSION": "1.9.19137",
  "BUILD_DATE": "2019-05-17",
  "BUILD_NUMBER": "2019_05_17__02_01",
  "COMPATIBILITY_VERSION": {
    "CONFIG_VERSION": "2"
  }
}

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/senzing-api-server/pull/52
