### ISSUE TITLE
Add entity resolution fields to SzEntityRecord when returned as part of an entity

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#51]
The array of for an SzResolvedEntity SzEntityRecord does not include the following fields:

MATCH_KEY
MATCH_SCORE
ERRULE_CODE
REF_SCORE
MATCH_LEVEL
Need to add these so we can tell the client "why" the record resolved to the entity.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/senzing-api-server/pull/52
