### ISSUE TITLE
Need to add a repository manager for auto testing.

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#55]
We need a way to create, load and purge Senzing repositories from the command-line for auto-testing.

Recommend:
```
java -cp senzing-api-server.jar com.senzing.repomgr.RepositoryManager [options]
```

OR
```
java -jar Senzing-api-server.jar -repo [options]
```

**Comment by docktermj** [comment]
Pull  Requests:

1. https://github.com/Senzing/senzing-api-server/pull/59
