### ISSUE TITLE
No endpoint to get the current or default config.

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#60]
Currently no way to access the raw configuration from the REST API -- only data sources and attribute types are available.

Add a new end-point to obtain the raw configuration.

Also need an endpoint for version information.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/senzing-api-server/pull/61
2. https://github.com/Senzing/senzing-api-server/pull/67
