### ISSUE TITLE
Add support for initV2() functions and auto reinitialization on config change

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#62]
Need to support initV2() functions for initialization via JSON file or environment variable or maybe even command line parameter.

Also need to detect config changes and automatically reinitialize.

**Comment by barrycaceres** [comment]
This was fixed in version 1.7.2

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/senzing-api-server/pull/68
