### ISSUE TITLE
Add maven dependencies for OpenJDK 11

### ISSUE THREAD

**Issue by bkci** [Senzing/senzing-api-server#64]
When building using OpenJDK 11, Oracle has removed all of the EE modules including javax.xml and javax.activation. 

The following dependencies will need to be added to the pom.xml file for anyone trying to build with OpenJDK 11:

\<dependency/>
  \<groupId/>javax.xml.bind\</groupId/>
  \<artifactId/>jaxb-api\</artifactId/>
  \<version/>2.3.0\</version/>
\</dependency/>
\<dependency/>
  \<groupId/>com.sun.xml.bind\</groupId/>
  \<artifactId/>jaxb-core\</artifactId/>
  \<version/>2.3.0\</version/>
\</dependency/>
\<dependency/>
  \<groupId/>com.sun.xml.bind\</groupId/>
  \<artifactId/>jaxb-impl\</artifactId/>
  \<version/>2.3.0\</version/>
\</dependency/>
\<dependency/>
  \<groupId/>com.sun.activation\</groupId/>
  \<artifactId/>javax.activation\</artifactId/>
  \<version/>1.2.0\</version/>
\</dependency/>

This should be added to the instructions for building.

**Comment by barrycaceres** [comment]
Currently JDK 1.8 is supported -- we will look into supporting newer versions of OpenJDK soon.

**Comment by docktermj** [comment]
@barrycaceres Is this still an issue? (cc: @bkci )

**Comment by barrycaceres** [comment]
We are upgrading to latest OpenJDK LTS (v11) and this will be taken into consideration during that process.  This is being addressed in the February/March 2020 sprint.

**Comment by barrycaceres** [comment]
Version 1.8.0 included the update to JDK 11
