### ISSUE TITLE
Maven version for OpenJDK 11

### ISSUE THREAD

**Issue by bkci** [Senzing/senzing-api-server#65]
Minimum maven version  for OpenJDK 11 is 3.6.1 as 3.6.0 has an incompatible guice version.

The instructions should be updated to reflect this requirement.

**Comment by barrycaceres** [comment]
Currently JDK 1.8 is supported.  We will look into supporting newer versions of OpenJDK soon.

**Comment by docktermj** [comment]
@barrycaceres Is this still an issue?  (cc: @bkci )

**Comment by barrycaceres** [comment]
This issue has been accepted and implementation is beginning during the February 2020 sprint.

**Comment by barrycaceres** [comment]
With the upgrade to JDK 11 in version 1.8.1 this has been corrected and the README now requires version 3.6.1 or later of Maven.
