### ISSUE TITLE
Errors when doing a docker-compose

### ISSUE THREAD

**Issue by ZackHill05** [Senzing/senzing-api-server#74]
When doing a docker-compose up, I get the following errors:     

senzing-api-server | The INI file must be specified.
senzing-api-server | java -jar senzing-api-server.jar <options>
senzing-api-server | <options> includes:
senzing-api-server |    -help
senzing-api-server |         Should be the first and only option if provided.
senzing-api-server |         Causes this help messasge to be displayed.
senzing-api-server |         NOTE: If this option is provided, the server will not start.
senzing-api-server |    -version
senzing-api-server |         Should be the first and only option if provided.
senzing-api-server |         Causes the version of the G2 REST API Server to be displayed.
senzing-api-server |         NOTE: If this option is provided, the server will not start.
senzing-api-server |    -httpPort [port-number]
senzing-api-server |         Sets the port for HTTP communication.  Defaults to 2080.
senzing-api-server |         Specify 0 for a randomly selected port number.
senzing-api-server |    -bindAddr [ip-address|loopback|all]
senzing-api-server |         Sets the port for HTTP bind address communication.
senzing-api-server |         Defaults to the loopback address.
senzing-api-server |    -allowedOrigins [url-domain]
senzing-api-server |         Sets the CORS Access-Control-Allow-Origin header for all endpoints.
senzing-api-server |         No Default.
senzing-api-server |    -concurrency [thread-count]
senzing-api-server |         Sets the number of threads available for executing
senzing-api-server |         Senzing API functions (i.e.: the number of engine threads).
senzing-api-server |         If not specified, then this defaults to 8.
senzing-api-server |    -moduleName [module-name]
senzing-api-server |         The module name to initialize with.  Defaults to 'ApiServer'.
senzing-api-server |    -iniFile [ini-file-path]
senzing-api-server |         The path to the Senzing INI file to with which to initialize.
senzing-api-server |    -verbose If specified then initialize in verbose mode.
senzing-api-server |    -monitorFile [filePath]
senzing-api-server |         Specifies a file whose timestamp is monitored to determine
senzing-api-server |         when to shutdown.
senzing-api-server exited with code 1

Is there an INI file I need to point to in a config?

**Comment by docktermj** [comment]
Over the last two weeks we've been migrating from a Senzing TGZ-based installation to an RPM-based installation.   

`senzing/senzing-api-server:latest` and `senzing/senzing-api-server:1.7.2` are based on the new RPM based installation.  To see a "full stack" of Senzing docker images that use the new RPM-based installation, visit https://github.com/Senzing/docker-compose-demo.  It was updated within the last week to reflect the new RPM-based installation.

If you'd like to continue using the TGZ-based installation approach for the near term,  you can specify the `senzing/senzing-api-server:1.6.1`  docker image explicitly.

Let me know if this is enough to get you going.  If not, paste your `docker-compose.yaml` contents in this issue so I can get better acquainted with the issue you are having.

References:

1. https://hub.docker.com/r/senzing/senzing-api-server/tags

**Comment by docktermj** [comment]
Here is an example of launching the new RPM-based `senzing/senzing-api-server`: 

https://github.com/Senzing/docker-compose-demo/blob/e98c330cfc3aff4b5a57ba83b11183ce12e406e4/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L116-L138

**Comment by ZackHill05** [comment]
Still having an error:

Creating network "senzing_backend" with the default driver
Creating senzing-api-server ... done
Creating senzing-api-server ...
Attaching to senzing-web-server, senzing-api-server
senzing-api-server |
senzing-api-server | The INI file must be specified.
senzing-api-server |
senzing-api-server | java -jar senzing-api-server.jar <options>
senzing-api-server |
senzing-api-server | <options> includes:
senzing-api-server |    -help
senzing-api-server |         Should be the first and only option if provided.
senzing-api-server |         Causes this help messasge to be displayed.
senzing-api-server |         NOTE: If this option is provided, the server will not start.
senzing-api-server |
senzing-api-server |    -version
senzing-api-server |         Should be the first and only option if provided.
senzing-api-server |         Causes the version of the G2 REST API Server to be displayed.
senzing-api-server |         NOTE: If this option is provided, the server will not start.
senzing-api-server |
senzing-api-server |    -httpPort [port-number]
senzing-api-server |         Sets the port for HTTP communication.  Defaults to 2080.
senzing-api-server |         Specify 0 for a randomly selected port number.
senzing-api-server |
senzing-api-server |    -bindAddr [ip-address|loopback|all]
senzing-api-server |         Sets the port for HTTP bind address communication.
senzing-api-server |         Defaults to the loopback address.
senzing-api-server |
senzing-api-server |    -allowedOrigins [url-domain]
senzing-api-server |         Sets the CORS Access-Control-Allow-Origin header for all endpoints.
senzing-api-server |         No Default.
senzing-api-server |
senzing-api-server |    -concurrency [thread-count]
senzing-api-server |         Sets the number of threads available for executing
senzing-api-server |         Senzing API functions (i.e.: the number of engine threads).
senzing-api-server |         If not specified, then this defaults to 8.
senzing-api-server |
senzing-api-server |    -moduleName [module-name]
senzing-api-server |         The module name to initialize with.  Defaults to 'ApiServer'.
senzing-api-server |
senzing-api-server |    -iniFile [ini-file-path]
senzing-api-server |         The path to the Senzing INI file to with which to initialize.
senzing-api-server |
senzing-api-server |    -verbose If specified then initialize in verbose mode.
senzing-api-server |
senzing-api-server |    -monitorFile [filePath]
senzing-api-server |         Specifies a file whose timestamp is monitored to determine
senzing-api-server |         when to shutdown.
senzing-api-server |
senzing-api-server |
senzing-web-server |
senzing-web-server | > @senzing/entity-search-web-app@1.0.2 start:docker /app
senzing-web-server | > node inject-env && node webserver
senzing-web-server |
senzing-web-server | SENZING_API_SERVER_URL: "http://api:8080"
senzing-web-server |
senzing-web-server | wrote proxy.conf
senzing-web-server |
senzing-web-server | [HPM] Proxy created: /  ->  http://api:8080
senzing-web-server | [HPM] Proxy rewrite rule created: "^/api" ~> ""
senzing-web-server | [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
senzing-web-server | Express Server started on port 8081
senzing-api-server exited with code 1
senzing-api-server | The INI file must be specified.
senzing-api-server | java -jar senzing-api-server.jar <options>
senzing-api-server | <options> includes:
senzing-api-server |    -help
senzing-api-server |         Should be the first and only option if provided.
senzing-api-server |         Causes this help messasge to be displayed.
senzing-api-server |         NOTE: If this option is provided, the server will not start.
senzing-api-server |    -version
senzing-api-server |         Should be the first and only option if provided.
senzing-api-server |         Causes the version of the G2 REST API Server to be displayed.
senzing-api-server |         NOTE: If this option is provided, the server will not start.
senzing-api-server |    -httpPort [port-number]
senzing-api-server |         Sets the port for HTTP communication.  Defaults to 2080.
senzing-api-server |         Specify 0 for a randomly selected port number.
senzing-api-server |    -bindAddr [ip-address|loopback|all]
senzing-api-server |         Sets the port for HTTP bind address communication.
senzing-api-server |         Defaults to the loopback address.
senzing-api-server |    -allowedOrigins [url-domain]
senzing-api-server |         Sets the CORS Access-Control-Allow-Origin header for all endpoints.
senzing-api-server |         No Default.
senzing-api-server |    -concurrency [thread-count]
senzing-api-server |         Sets the number of threads available for executing
senzing-api-server |         Senzing API functions (i.e.: the number of engine threads).
senzing-api-server |         If not specified, then this defaults to 8.
senzing-api-server |    -moduleName [module-name]
senzing-api-server |         The module name to initialize with.  Defaults to 'ApiServer'.
senzing-api-server |    -iniFile [ini-file-path]
senzing-api-server |         The path to the Senzing INI file to with which to initialize.
senzing-api-server |    -verbose If specified then initialize in verbose mode.
senzing-api-server |    -monitorFile [filePath]
senzing-api-server |         Specifies a file whose timestamp is monitored to determine
senzing-api-server |         when to shutdown.

Don't know if that means server-api is good and web is bad. docker-compose.yaml is:
version: '2'
services:

  api:
    image: senzing/senzing-api-server:1.6.1
    container_name: senzing-api-server
    environment:
      SENZING_OPTIONS: ""
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - /app/senzing:/opt/senzing
      - /app/vmdk:/app/vmdk
    restart: always

  webui:
    image: senzing/entity-search-web-app
    container_name: senzing-web-server
    environment:
      SENZING_API_SERVER_URL: "http://api:8080"
      SENZING_WEB_SERVER_PORT: 8081
      SENZING_WEB_SERVER_API_PATH: '/api'
    networks:
      - backend
    ports:
      - 8081:8081

    restart: always

networks:
  backend:

and doing a sudo docker images is:
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
senzing/entity-search-web-app   latest              d615925b4f37        2 weeks ago         1.88 GB
senzing/senzing-api-server      1.6.1               7d217f15ffec        2 months ago        1.12 GB

I tried to pull entity-search-web-app:1.6.1 but got an error that the manifest doesn't exist.

**Comment by ZackHill05** [comment]
Thanks Mike! That got me past the error. However, when I do a search in the web UI, I get this error in the log:

^[[33msenzing-web-server |^[[0m [HPM] Rewriting path from "/api/attribute-types" to "/attribute-types"
^[[33msenzing-web-server |^[[0m [HPM] GET /api/attribute-types ~> http://api:8080
^[[33msenzing-web-server |^[[0m [HPM] Error occurred while trying to proxy request /attribute-types from zeleznik.us.lmco.com:8081 to http://api:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
^[[33msenzing-web-server |^[[0m [HPM] Rewriting path from "/api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D" to "/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D"
^[[33msenzing-web-server |^[[0m [HPM] GET /api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D ~> http://api:8080
^[[33msenzing-web-server |^[[0m [HPM] Error occurred while trying to proxy request /entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D from zeleznik.us.lmco.com:8081 to http://api:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
^[[33msenzing-web-server |^[[0m [HPM] Rewriting path from "/api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jonesls%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jonesls%22%7D" to "/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jonesls%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jonesls%22%7D"
^[[33msenzing-web-server |^[[0m [HPM] GET /api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jonesls%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jonesls%22%7D ~> http://api:8080
^[[33msenzing-web-server |^[[0m [HPM] Error occurred while trying to proxy request /entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jonesls%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jonesls%22%7D from zeleznik.us.lmco.com:8081 to http://api:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)


The image is senzing/entity-search-web-app and is using the latest version. 

Also, I get a 404 error when trying to go to https://cloud.docker.com/u/senzing/repository/docker/senzing/entity-search-web-app/tags and https://cloud.docker.com/u/senzing/repository/docker/senzing/senzing-api-server/tags, so I can't see the version I can pull for entity-search-web-app.

**Comment by ZackHill05** [comment]
@arawinters made that change and I still get the following error (putting entire log to see if that helps):

Recreating senzing-web-server ... ^M
senzing-api-server is up-to-date
^[[1A^[[2K^MRecreating senzing-web-server ... ^[[32mdone^[[0m^M^[[1BAttaching to senzing-api-server, senzing-web-server
^[[36msenzing-api-server |^[[0m os.arch        = amd64
^[[36msenzing-api-server |^[[0m os.name        = Linux
^[[36msenzing-api-server |^[[0m user.dir       = /app
^[[36msenzing-api-server |^[[0m user.home      = /root
^[[36msenzing-api-server |^[[0m java.io.tmpdir = /tmp
^[[36msenzing-api-server |^[[0m Created Senzing engine thread pool with 8 thread(s).
^[[36msenzing-api-server |^[[0m 2019-08-28 13:44:29.815:INFO::main: Logging initialized @493ms to org.eclipse.jetty.util.log.StdErrLog
^[[36msenzing-api-server |^[[0m Starting Senzing REST API Server on port 2080....
^[[36msenzing-api-server |^[[0m Started Senzing REST API Server on port 2080.
^[[36msenzing-api-server |^[[0m Server running at:
^[[36msenzing-api-server |^[[0m http://127.0.0.1:2080/
^[[33msenzing-web-server |^[[0m
^[[33msenzing-web-server |^[[0m > @senzing/entity-search-web-app@1.0.2 start:docker /app
^[[33msenzing-web-server |^[[0m > node inject-env && node webserver
^[[33msenzing-web-server |^[[0m
^[[33msenzing-web-server |^[[0m SENZING_API_SERVER_URL: "http://senzing-api-server:8080"
^[[33msenzing-web-server |^[[0m
^[[33msenzing-web-server |^[[0m wrote proxy.conf
^[[33msenzing-web-server |^[[0m
^[[33msenzing-web-server |^[[0m [HPM] Proxy created: /  ->  http://senzing-api-server:8080
^[[33msenzing-web-server |^[[0m [HPM] Proxy rewrite rule created: "^/api" ~> ""
^[[33msenzing-web-server |^[[0m [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
^[[33msenzing-web-server |^[[0m Express Server started on port 8081
^[[33msenzing-web-server |^[[0m [HPM] Rewriting path from "/api/attribute-types" to "/attribute-types"
^[[33msenzing-web-server |^[[0m [HPM] GET /api/attribute-types ~> http://senzing-api-server:8080
^[[33msenzing-web-server |^[[0m [HPM] Error occurred while trying to proxy request /attribute-types from zeleznik.us.lmco.com:8081 to http://senzing-api-server:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
^[[33msenzing-web-server |^[[0m [HPM] Rewriting path from "/api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D" to "/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D"
^[[33msenzing-web-server |^[[0m [HPM] GET /api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D ~> http://senzing-api-server:8080
^[[33msenzing-web-server |^[[0m [HPM] Error occurred while trying to proxy request /entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D from zeleznik.us.lmco.com:8081 to http://senzing-api-server:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^[[33msenzing-web-server |^[[0m
^[[33msenzing-web-server |^[[0m ┌──────────────────────────────────────────────┐
^[[33msenzing-web-server |^[[0m │           npm update check failed            │
^[[33msenzing-web-server |^[[0m │     Try running with sudo or get access      │
^[[33msenzing-web-server |^[[0m │     to the local update config store via     │
^[[33msenzing-web-server |^[[0m │ sudo chown -R $USER:$(id -gn $USER) /.config │
^[[33msenzing-web-server |^[[0m └──────────────────────────────────────────────┘
^[[33msenzing-web-server exited with code 0
^[[0m^[[32msenzing-web-server |^[[0m > @senzing/entity-search-web-app@1.0.2 start:docker /app
^[[32msenzing-web-server |^[[0m > node inject-env && node webserver
^[[32msenzing-web-server |^[[0m SENZING_API_SERVER_URL: "http://senzing-api-server:8080"
^[[32msenzing-web-server |^[[0m wrote proxy.conf
^[[32msenzing-web-server |^[[0m [HPM] Proxy created: /  ->  http://senzing-api-server:8080
^[[32msenzing-web-server |^[[0m [HPM] Proxy rewrite rule created: "^/api" ~> ""
^[[32msenzing-web-server |^[[0m [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
^[[32msenzing-web-server |^[[0m Express Server started on port 8081
^[[32msenzing-web-server |^[[0m [HPM] Rewriting path from "/api/attribute-types" to "/attribute-types"
^[[32msenzing-web-server |^[[0m [HPM] GET /api/attribute-types ~> http://senzing-api-server:8080
^[[32msenzing-web-server |^[[0m [HPM] Error occurred while trying to proxy request /attribute-types from zeleznik.us.lmco.com:8081 to http://senzing-api-server:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
^[[32msenzing-web-server |^[[0m [HPM] Rewriting path from "/api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D" to "/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D"
^[[32msenzing-web-server |^[[0m [HPM] GET /api/entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D ~> http://senzing-api-server:8080
^[[32msenzing-web-server |^[[0m [HPM] Error occurred while trying to proxy request /entities?attrs=%7B%22NAME_FULL%22:%22Robert%20Jones%22,%22NAME_TYPE%22:%22PRIMARY%22,%22COMPANY_NAME_ORG%22:%22Robert%20Jones%22%7D from zeleznik.us.lmco.com:8081 to http://senzing-api-server:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by docktermj** [comment]
@ZackHill05 Is this still an issue?

**Comment by ZackHill05** [comment]
@docktermj yes I am in the original environment, but we're now setting up the production environment. For that environment, I have installed the latest senzing-api-server and senzing-entity-search-web-app, and put docker-compose.yaml version 3 on the system. I think I need help configuring the docker-compose.yaml file. Could we have a quick meeting?

**Comment by docktermj** [comment]
@ZackHill05 Just checking in.  Did we resolve this to your satisfaction?

**Comment by ZackHill05** [comment]
@docktermj yes, this is resolved to my satisfaction. We should no longer have a need to have a test environment.
