### ISSUE TITLE
Support web app loading entire JSON or CSV files rather than record by record

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#77]
This is issue is simply to add whatever support is needed for loading files through the web app in stateless manner.

**Comment by ZackHill05** [comment]
@docktermj @barrycaceres  Any update on adding this support? The ETL I'm using would really benefit from having this functionality.

**Comment by brianmacy** [comment]
I noticed this is described as a WebApp issue but is logged against the REST server.  Should this be moved or are we talking about bulk add to the REST server?  I would recommend against the latter and instead use MQ loading support for bulk loads.

**Comment by ZackHill05** [comment]
@docktermj @barrycaceres @brianmacy  As a consumer of the Senzing REST APIs, I'd like to have something in the middle of "synchronous, but one record at a time" and "asynchronous, but bulk load". Why can't I have "synchronous, multiple records, but with a limit". Basically allow me to put up to X records in the request body (would be nice if X was 100K or 1M), and I took "stateless" to mean you really don't get a response other than "I got it, I'm working it".

Does that make sense?

**Comment by brianmacy** [comment]
Got it.  So what you want is the ability to parallelize processing a block of records in a single call and then aggregate the responses (if any) into a single response via the REST API.

If so, that currently isn't on the roadmap (that said, this is an open source project).  The solution to that with the existing architectures available would be to use the stream loader w/ RabbitMQ/Khafka and have it publish any responses to another RabbitMQ/Khafka.

**Comment by ZackHill05** [comment]
Thanks for the quick response Brian! If that's the case, would it make sense to close this issue? Having it open gives people like me hope :).

**Comment by brianmacy** [comment]
Enhancement requests are good and it isn't that it is invalid, there is just a different approach in place.  If we have added issue voting (have we?) or someone wants to contribute a solution then it could get scheduled.

My concerns about the bulk API operations come down to the limitations:
1. A REST API is really going to only scale to 4-16 engine threads.  So you have to scale out clients, REST servers, and add a load balancer in front pretty quickly on a system of significant size.
2. During a bulk load, you will significantly impact interactive operations.  For instance, FIFO behavior could easily cause the back end pool of engine instances to be saturated by 100+ records operation for 2-5seconds or more.  To get around it you would need either priority queue (likely more latency) and/or separate REST API instances for separate workloads.

In the stream-loader, the architecture by its nature avoids these issues.  But it isn't that these can't be overcome or that such an ability wouldn't be useful.

**Comment by docktermj** [comment]
@ZackHill05 I'd like to keep this issue open for discussion.   Here's a thought:

In things like Fluend, Logstash, and Apache Spark Streaming, there's a concept of "micro-batch".   This is a small set of messages that are processed. Not quite the 100k -1M, but maybe in the hundreds or low thousands.

This allows micro-service environments that scale up (e.g. Kubernetes pods) to each take a single "micro-batch" to process.   That way if there's a failure, it's only a few message that need to be reprocessed, not 100K.  Performance is increased by scaling up the number of pods. The requests are load balanced by Kubernetes.   This is an improvement over single "pod" processing 100K - 1M messages, there would be no way to horizontally scale up to improve performance -- and recovering from failure would be miserable.

A micro-batch implementation also avoids issues like: 
1. HTTP 413 errors 
2. Timeouts on the client side

**Comment by barrycaceres** [comment]
> @docktermj @barrycaceres @brianmacy As a consumer of the Senzing REST APIs, I'd like to have something in the middle of "synchronous, but one record at a time" and "asynchronous, but bulk load". Why can't I have "synchronous, multiple records, but with a limit". Basically allow me to put up to X records in the request body (would be nice if X was 100K or 1M), and I took "stateless" to mean you really don't get a response other than "I got it, I'm working it".
> 
> Does that make sense?

I believe what you describe here is what we are adding in our first round of bulk-loading via the API Server.  It will take a file upload in the HTTP request and return a response once the entire file has been loaded (concurrently loading records and waiting for all to complete).  There will be an option to send a request header of `Accept: text/event-stream` which will allow the response to take the form of "Server-Sent Events" (SSE) with periodic updates of progress on a single long-lived HTTP request with the final event indicating the completion (or abort) of the load.

Does that sound like what you are asking for?

**Comment by barrycaceres** [comment]
Bulk data load is included in version 1.8.0 of the API Server.
