### ISSUE TITLE
The "GET /version" endpoint should define "configCompatibilityVersion" as a string

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#82]
The `GET /version` endpoint defined the `configCompatbilityVersion` response field as an integer rather than a string -- preventing the use semantic versioning.  This was a bug that needs to be corrected and may cause some clients to break unless regenerated as they may attempt to parse the result as an integer.

**Comment by barrycaceres** [comment]
Fixed in 1.7.5

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/senzing-api-server/pull/

83
