### ISSUE TITLE
Security warnings on FasterXML Jackson & Error checks in Config Manager impl

### ISSUE THREAD

**Issue by barrycaceres** [Senzing/senzing-api-server#87]
Need to update code to check for errors when initializing config manager and also update FasterXML Jackson dependencies to resolve security issue.

**Comment by barrycaceres** [comment]
Version 1.7.6 fixes this.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/senzing-api-server/pull/89
